data: ./example_data/simple_gam/X.csv
target: ./example_data/simple_gam/Y.csv
output_dir: ./outputs
mode: train
load_model: ./outputs/model.pth

distribution: Poisson
formulas: {rate: '~1+spline(x1, bs="bs",df=9)+spline(x2, bs="bs",df=9)+d1(x1)+d2(x2)'
}

deep_models_dict: {
  d1: {
    model: 'TestNet(n_channels=1, n_classes=15)', #'nn.Sequential(nn.Linear(1,15))',
    output_shape: 15},
  d2: {
    model: 'nn.Sequential(nn.Linear(1,3),nn.ReLU(), nn.Linear(3,8))',
     output_shape: 8}
}

train_parameters: {
  batch_size: 1000,
  epochs: 1000,
  optimizer: 'optim.SGD',
  optimizer_params: {lr: 0.01, momentum: 0.9}, 
  degrees_of_freedom: {rate: 10}
}