data_path: '/data/data.csv'
ground_truth_path: '/data/ground_truth.csv'
output_dir: './outputs'

current_distribution: normal
formulas: {location: '~1+spline(x1, bs="bs",df=9)+spline(x2, bs="bs",df=9)+d1(x1)+d2(x2)',
            scale: '~1+spline(x2, bs="bs",df=9)'
}

deep_shapes: {
  n1: 3,
  n2: 1
}
deep_models_dict: {
  d1: [nn.Sequential(nn.Linear(1,15))],
  d2: nn.Sequential(nn.Linear(1,3),nn.ReLU(), nn.Linear(3,8))
}

train_parameters: {
  batch_size: 1,
  epochs: 5,
  regularization_params: 1
}