data_path: './example_data/simple_gam/X.csv'
ground_truth_path: './example_data/simple_gam/Y.csv'
output_dir: './outputs'

current_distribution: 'Poisson'
formulas: {'rate': '~1+spline(x1, bs="bs",df=9)+spline(x2, bs="bs",df=9)+d1(x1)+d2(x2)'
}

deep_models_dict: {
  d1: {
    model: 'nn.Sequential(nn.Linear(1,15))',
    output_shape: 15},
  d2: {
    model: 'nn.Sequential(nn.Linear(1,3),nn.ReLU(), nn.Linear(3,8))',
     output_shape: 8}
}

train_parameters: {
  batch_size: 1000,
  epochs: 1000,
  regularization_params: {'rate': 1}
}