deep_models_dict:
  dnn:
    model: "Sequential(\n  (0): Flatten(start_dim=1, end_dim=-1)\n  (1): Linear(in_features=784,\
      \ out_features=32, bias=False)\n  (2): ReLU()\n  (3): Linear(in_features=32,\
      \ out_features=16, bias=True)\n  (4): ReLU()\n)"
    output_shape: 0
distribution: Normal
formulas:
  loc: ~ 1 + X1
  scale: ~ 1
modify: true
ortho_manual: false
output_dir: /scratch/slurm_tmpdir/job_1504668/outputs_linear_a_X1
train_parameters:
  batch_size: 32
  degrees_of_freedom:
    loc: 10
    scale: 10
  early_stop_epsilon: 0.001
  epochs: 100
  optimizer: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach:\
    \ None\n    fused: None\n    lr: 0.001\n    maximize: False\n    weight_decay:\
    \ 0\n)"
  val_split: 0.15
