deep_models_dict:
  dnn:
    model: "Sequential(\n  (0): Flatten(start_dim=1, end_dim=-1)\n  (1): Linear(in_features=784,\
      \ out_features=32, bias=False)\n  (2): ReLU()\n  (3): Linear(in_features=32,\
      \ out_features=16, bias=True)\n)"
    output_shape: 0
distribution: Normal
formulas:
  loc: ~ 1 + spline(Z1, bs='bs', df=9) + spline(Z2, bs='bs', df=9)
  scale: ~ 1
modify: false
n_knots: 6
ortho_manual: false
output_dir: ./outputs_nonlinear_nknots_6_batch_32
train_parameters:
  batch_size: 32
  degrees_of_freedom:
    loc: 9
    scale: 9
  early_stop_epsilon: 0.001
  epochs: 100
  optimizer: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach:\
    \ None\n    fused: None\n    lr: 0.001\n    maximize: False\n    weight_decay:\
    \ 0\n)"
  val_split: 0.15
use_spline_for_struct: false
